# Home
interim_informatique_homepage:
    pattern:  /
    defaults: { _controller: InterimInformatiqueBundle:Front:index }


# Jobs seekers
interim_informatique_jobseekers:
    pattern:  /collaborateurs
    defaults: { _controller: InterimInformatiqueBundle:JobSeeker:index }

interim_informatique_add_jobseeker:
    pattern:  /collaborateur/ajouter
    defaults: { _controller: InterimInformatiqueBundle:JobSeeker:add }


interim_informatique_infos_jobseeker:
    pattern:  /collaborateur/{id}
    defaults: { _controller: InterimInformatiqueBundle:JobSeeker:infos }
    requirements:
        id : \d+

interim_informatique_edit_jobseeker:
    pattern:  /collaborateur/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:JobSeeker:edit }
    requirements:
        id : \d+

# Companies
interim_informatique_companies:
    pattern:  /entreprises
    defaults: { _controller: InterimInformatiqueBundle:Company:index }

interim_informatique_add_company:
    pattern:  /entreprise/ajouter
    defaults: { _controller: InterimInformatiqueBundle:Company:add }

interim_informatique_infos_company:
    pattern:  /entreprise/{id}
    defaults: { _controller: InterimInformatiqueBundle:Company:infos }
    requirements:
        id : \d+

interim_informatique_edit_company:
    pattern:  /entreprise/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:Company:edit }
    requirements:
        id : \d+

# Jobs
interim_informatique_jobs:
    pattern:  /offres
    defaults: { _controller: InterimInformatiqueBundle:Job:index }


interim_informatique_add_job:
    pattern:  /offre/ajouter
    defaults: { _controller: InterimInformatiqueBundle:Job:add }


interim_informatique_infos_job:
    pattern:  /offre/{id}
    defaults: { _controller: InterimInformatiqueBundle:Job:infos }
    requirements:
        id : \d+

interim_informatique_edit_job:
    pattern:  /offre/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:Job:edit }
    requirements:
        id : \d+


# Configuration Routing

interim_informatique_configuration_skills:
    pattern:  /configuration/competences
    defaults: { _controller: InterimInformatiqueBundle:Skill:index }

interim_informatique_configuration_business_sectors:
    pattern:  /configuration/secteurs-activites
    defaults: { _controller: InterimInformatiqueBundle:BusinessSector:index }

interim_informatique_configuration_kind_contracts:
    pattern:  /configuration/types-de-contrats
    defaults: { _controller: InterimInformatiqueBundle:KindContract:index }

interim_informatique_configuration_diplomas:
    pattern:  /configuration/diplomes
    defaults: { _controller: InterimInformatiqueBundle:Diploma:index }
    
interim_informatique_configuration_diplomas_levels:
    pattern:  /configuration/niveaux-diplomes
    defaults: { _controller: InterimInformatiqueBundle:DiplomaLevel:index }


# Add
 
interim_informatique_configuration_add_business_sector:
    pattern:  /configuration/secteur-activite/ajouter
    defaults: { _controller: InterimInformatiqueBundle:BusinessSector:add }

interim_informatique_configuration_add_kind_contract:
    pattern:  /configuration/type-de-contrat/ajouter
    defaults: { _controller: InterimInformatiqueBundle:KindContract:add }

interim_informatique_configuration_add_diploma:
    pattern:  /configuration/diplome/ajouter
    defaults: { _controller: InterimInformatiqueBundle:Diploma:add }

interim_informatique_configuration_add_diploma_level:
    pattern:  /configuration/niveau-diplome/ajouter
    defaults: { _controller: InterimInformatiqueBundle:DiplomaLevel:add }

interim_informatique_configuration_add_skill:
    pattern:  /configuration/competence/ajouter
    defaults: { _controller: InterimInformatiqueBundle:Skill:add }




# Get infos

interim_informatique_configuration_infos_business_sector:
    pattern:  /configuration/secteur-activite/{id}
    defaults: { _controller: InterimInformatiqueBundle:BusinessSector:infos }
    requirements:
        id : \d+

interim_informatique_configuration_infos_kind_contract:
    pattern:  /configuration/type-de-contrat/{id}
    defaults: { _controller: InterimInformatiqueBundle:BusinessSector:infos }
    requirements:
        id : \d+

interim_informatique_configuration_infos_diploma:
    pattern:  /configuration/diplome/{id}
    defaults: { _controller: InterimInformatiqueBundle:Diploma:infos }
    requirements:
        id : \d+

interim_informatique_configuration_infos_diploma_level:
    pattern:  /configuration/niveau-diplome/{id}
    defaults: { _controller: InterimInformatiqueBundle:DiplomaLevel:infos }
    requirements:
        id : \d+

interim_informatique_configuration_infos_skill:
    pattern:  /configuration/competence/{id}
    defaults: { _controller: InterimInformatiqueBundle:Skill:infos }
    requirements:
        id : \d+

# Edit
 
interim_informatique_configuration_edit_business_sector:
    pattern:  /configuration/secteur-activite/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:BusinessSector:edit }
    requirements:
        id : \d+
        
interim_informatique_configuration_edit_kind_contract:
    pattern:  /configuration/type-de-contrat/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:KindContract:edit }
    requirements:
        id : \d+
        
interim_informatique_configuration_edit_diploma:
    pattern:  /configuration/diplome/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:Diploma:edit }
    requirements:
        id : \d+
        
interim_informatique_configuration_edit_diploma_level:
    pattern:  /configuration/niveau-diplome/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:DiplomaLevel:edit }
    requirements:
        id : \d+
        
interim_informatique_configuration_edit_skill:
    pattern:  /configuration/competence/modifier/{id}
    defaults: { _controller: InterimInformatiqueBundle:Skill:edit }
    requirements:
        id : \d+