<?php

namespace Interim\InformatiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiplomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomaRepository extends EntityRepository
{

    public function getDiplomaWithLevel() {
        $qb = $this->createQueryBuilder('d')
                ->leftJoin('d.diplomaLevel', 'dl')
                ->addSelect('dl')
                ->addOrderBy('dl.orderLevel', 'ASC')
                ->addOrderBy('d.name', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
