<?php

namespace Interim\InformatiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobSeekerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerRepository extends EntityRepository
{
}
