<?php

namespace Interim\InformatiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends EntityRepository
{

    public function getSkillsByOrder() {
        $qb = $this->createQueryBuilder('s')
                ->orderBy('s.name', 'ASC');

        return $qb;
    }

}
